# Generated by Django 4.1.7 on 2023-03-12 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_game_black_game_date_game_event_game_result_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='eco',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='ecot',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='opening',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='openingt',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='variation',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='variationt',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
